# Generated by Django 4.1 on 2022-09-10 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_remove_listing_submit_bid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bid',
            options={'ordering': ('-amount',)},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('time',)},
        ),
        migrations.AlterModelOptions(
            name='listing',
            options={'ordering': ('end_time',)},
        ),
    ]
